name: 'remote-build'
description: 'Builds a Docker image for a Python poetry project.'
inputs:
  dockerhub_repo:
    required: true
  dockerhub_username:
    required: true
  dockerhub_password:
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}
    - run: pip install git+https://github.com/mishajw/remote
      shell: bash
    - run: |
        GIT_SHA=$(git rev-parse --short HEAD)
        IMAGE_NAME="${{ inputs.dockerhub_username }}/${{ inputs.dockerhub_repo }}:$GIT_SHA"
        remote build $IMAGE_NAME
      shell: bash
